using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AecCloud.MFilesCore
{
    public static class MfilesAliasConfig
    {
        public static string VlContractedProfession = "VlContractedProfession";
        public static string VlProvince = "VlProvince";
        public static string VlCity = "VlCity";
        public static string VLIsQualified = "VLIsQualified";
        public static string VlSecureCategory = "VlSecureCategory";

        public static string UgErpPrincipal = "UgErpPrincipal";
         public static string UgQualityInspector = "UgQualityInspector";
         public static string UgSafetySupervisor = "UgSafetySupervisor";
         public static string UgProjectBusinessManager = "UgProjectBusinessManager";
         public static string UGroupPM = "UGroupPM";
        public static string UgBigChiefEngineer = "UgBigChiefEngineer";
        public static string UGroupVicePM = "UGroupVicePM";
        public static string UgChiefEngineer = "UgChiefEngineer";
        public static string UgViceExecutive = "UgViceExecutive";
        public static string UgSecurityGuard = "UgSecurityGuard";
        public static string UgEngineeringManagementDepartment = "UgEngineeringManagementDepartment";
        public static string UgSafetyProductionManagementDepartment = "UgSafetyProductionManagementDepartment";
        public static string UgHeadquartersEngineeringManagementDepartment = "UgHeadquartersEngineeringManagementDepartment";
        public static string UgProjectSecretary = "UgProjectSecretary";
        public static string UgSecondLevelChiefEconomist = "UgSecondLevelChiefEconomist";
        public static string UgSecondLevelDeputyManager = "UgSecondLevelDeputyManager";
        public static string UgSecondLevelManager = "UgSecondLevelManager";
        public static string UgLegalServiceManager = "UgLegalServiceManager";
        public static string UgHeadquartersEngineeringManager = "UgHeadquartersEngineeringManager";
        public static string UgBusinessManager = "UgBusinessManager";
        public static string UgSecondLevelChiefEngineer = "UgSecondLevelChiefEngineer";
        public static string UgSecondLevelBusinessManager = "UgSecondLevelBusinessManager";
        public static string UgOfficeManagerSecondLevel = "UgOfficeManagerSecondLevel";
        
        public static string UgHeadquartersGeneralManager = "UgHeadquartersGeneralManager";
        public static string UgChiefEconomist = "UgChiefEconomist";
        public static string UgChiefAccountant = "UgChiefAccountant";
        public static string UgSecondLevelChiefAccountant = "UgSecondLevelChiefAccountant";
        public static string UgHumenResourceManager = "UgHumenResourceManager";
        public static string UgBusinessManagementManager = "UgBusinessManagementManager";
        public static string UgMaterialManager = "UgMaterialManager";
        public static string UgHeadquartersScienceManager = "UgHeadquartersScienceManager";
        public static string UgHeadquartersTechCenterManager = "UgHeadquartersTechCenterManager";
        public static string UgHeadquartersFundsManager = "UgHeadquartersFundsManager";
        public static string UgOfficeManager = "UgOfficeManager";
        public static string UgConstructionManager = "UgConstructionManager";
        public static string UgMaterialManagerSecondLevel = "UgMaterialManagerSecondLevel";
        public static string UgFinanceManager = "UgFinanceManager";
        public static string UgHLeaders = "Ug.H.Leaders";
        public static string UgSecondLevelLeaders = "UgSecondLevelLeaders";
        public static string UgHeadquartersBusinessDepartment = "UgHeadquartersBusinessDepartment";
        public static string UgHeadquartersTechnologyDepartment = "UgHeadquartersTechnologyDepartment";
        public static string UgHeadquartersFinanceDepartment = "UgHeadquartersFinanceDepartment";
        public static string UgSafetyProductionManagementDeptManager = "UgSafetyProductionManagementDeptManager";
        public static string UgEngineeringManagerSecond = "UgEngineeringManagerSecond";
        public static string UgSecondLevelFinanceManager = "UgSecondLevelFinanceManager";
        public static string UgGeneralContractingManager = "UgGeneralContractingManager";

        public static string InvestigateUnit = "InvestigateUnit";
         public static string PmUnit = "PmUnit";
         public static string PropSpecifiedVerifier = "PropSpecifiedVerifier";
        public static string PropCompletionDate = "PropCompletionDate";
          public static string PropQualityAdjustmentReceiver = "PropQualityAdjustmentReceiver";
         public static string PropAcceptingUnit = "PropAcceptingUnit";
         public static string PropProjectBasicInfo = "PropProjectBasicInfo";
         public static string PropNameAndCoding = "PropNameAndCoding";
         public static string PropReportDate = "PropReportDate";
        public static string PropFundamentalAcceptanceCertificateAttachment = "PropFundamentalAcceptanceCertificateAttachment";
         public static string PropPincipalPartAcceptanceCertificateAttachment = "PropPincipalPartAcceptanceCertificateAttachment";
         public static string PropFinishedAcceptanceCertificateAttachment = "PropFinishedAcceptanceCertificateAttachment";
         public static string PropFundsManagementScore = "PropFundsManagementScore";
         public static string PropFundsManagementOpinion = "PropFundsManagementOpinion";
         public static string PropQualityTechnologyManagementScore = "PropQualityTechnologyManagementScore";
         public static string PropQualityTechnologyManagementOpinion = "PropQualityTechnologyManagementOpinion";
         public static string PropInformatizationManagementScore = "PropInformatizationManagementScore";
        public static string PropInformatizationManagementOpinion = "PropInformatizationManagementOpinion";
         public static string PropMaterialManagementScore = "PropMaterialManagementScore";
        public static string PropMaterialManagementOpinion = "PropMaterialManagementOpinion";
         public static string PropSecureEnvironmentalManagementScore = "PropSecureEnvironmentalManagementScore";
        public static string PropSecureEnvironmentalManagementOpinion = "PropSecureEnvironmentalManagementOpinion";
         public static string PropProgressContractorPlanScore = "PropProgressContractorPlanScore";
        public static string PropProgressContractorPlanOpinion = "PropProgressContractorPlanOpinion";
          public static string PropCostManagementScore = "PropCostManagementScore";
          public static string PropCostManagementOpinion = "PropCostManagementOpinion";
         public static string PropContractAdministrationScore = "PropContractAdministrationScore";
        public static string PropContractAdministrationOpinion = "PropContractAdministrationOpinion";
         public static string PropTeamBuildingScore = "PropTeamBuildingScore";
         public static string PropTeamBuildingOpinion = "PropTeamBuildingOpinion";
         public static string PropGreenConstructionManagementScore = "PropGreenConstructionManagementScore";
         public static string PropGreenConstructionManagementScoreSecondLevel = "PropGreenConstructionManagementScoreSecondLevel";
         public static string PropFundsManagementScoreSecondLevel = "PropFundsManagementScoreSecondLevel";
         public static string PropFundsManagementOpinionSecondLevel = "PropFundsManagementOpinionSecondLevel";
         public static string PropQualityTechnologyManagementScoreSecondLevel = "PropQualityTechnologyManagementScoreSecondLevel";
         public static string PropQualityTechnologyManagementOpinionSecondLevel = "PropQualityTechnologyManagementOpinionSecondLevel";
         public static string PropInformatizationManagementScoreSecondLevel = "PropInformatizationManagementScoreSecondLevel";
         public static string PropInformatizationManagementOpinionSecondLevel = "PropInformatizationManagementOpinionSecondLevel";
         public static string PropMaterialManagementScoreSecondLevel = "PropMaterialManagementScoreSecondLevel";
         public static string PropMaterialManagementOpinionSecondLevel = "PropMaterialManagementOpinionSecondLevel";
         public static string PropSecureEnvironmentalManagementScoreSecondLevel = "PropSecureEnvironmentalManagementScoreSecondLevel";
         public static string PropSecureEnvironmentalManagementOpinionSecondLevel = "PropSecureEnvironmentalManagementOpinionSecondLevel";
         public static string PropProgressContractorPlanScoreSecondLevel = "PropProgressContractorPlanScoreSecondLevel";
         public static string PropProgressContractorPlanOpinionSecondLevel = "PropProgressContractorPlanOpinionSecondLevel";
         public static string PropCostManagementScoreSecondLevel = "PropCostManagementScoreSecondLevel";
         public static string PropCostManagementOpinionSecondLevel = "PropCostManagementOpinionSecondLevel";
         public static string PropContractAdministrationScoreSecondLevel = "PropContractAdministrationScoreSecondLevel";
         public static string PropContractAdministrationOpinionSecondLevel = "PropContractAdministrationOpinionSecondLevel";
         public static string PropTeamBuildingScoreSecondLevel = "PropTeamBuildingScoreSecondLevel";
         public static string PropTeamBuildingOpinionSecondLevel = "PropTeamBuildingOpinionSecondLevel";

         public static string PropAfterPictures = "PropAfterPictures";
         public static string PropBeforePictures = "PropBeforePictures";
          public static string PropSecureIssues = "PropSecureIssues";
         public static string PropFuChaRen = "PropFuChaRen";
          public static string PropZhengGaiQiXin = "PropZhengGaiQiXin";
         public static string PropReviewDate = "PropReviewDate";
         public static string PropRectificationCount = "PropRectificationCount";
         public static string PropCountercheckDescription = "PropCountercheckDescription";
        public static string PropCheckDate = "PropCheckDate";
        public static string PropSecureReceiver = "PropSecureReceiver";
         public static string PropPrincipal = "PropPrincipal";
         public static string PropAdjustMan = "PropAdjustMan";
        public static string PropAdjustMeasure = "PropAdjustMeasure";
        public static string PropSecureAdjustDate = "PropSecureAdjustDate";
        public static string PropContractorName = "PropContractorName";
        public static string PropContractedProfession = "PropContractedProfession";
        public static string PropBusinessLicenseNumber = "PropBusinessLicenseNumber";
        public static string PropTaxRegistrationNumber = "PropTaxRegistrationNumber";
        public static string PropQualificationCertificateNumber = "PropQualificationCertificateNumber";
        public static string PropLevelOfQualification = "PropLevelOfQualification";
        public static string PropIssueCategory = "PropIssueCategory";
        public static string PropSafetyProductionLicenseNumber = "PropSafetyProductionLicenseNumber";
        public static string PropRegisteredCapital = "PropRegisteredCapital";
        public static string PropTelephoneAndFaxOfLegalRepresentative = "PropTelephoneAndFaxOfLegalRepresentative";
        public static string PropDetailedAddress = "PropDetailedAddress";
        public static string PropDeputiesAndTelephones = "PropDeputiesAndTelephones";
        public static string PropLevel = "PropLevel";
        public static string PropIsQualified = "PropIsQualified";
        public static string PropComment = "PropComment";
        public static string PropMonthReportName = "PropMonthReportName";
        public static string PropReportMonth = "PropReportMonth";
        public static string PropDelayDays = "PropDelayDays";
        public static string PropPlanFinishDate = "PropPlanFinishDate";
        public static string PropPrincipalPartPlanDate = "PropPrincipalPartPlanDate";
        public static string PropFundamentalPlanDate = "PropFundamentalPlanDate";
        public static string PropFundamentalCloseDate = "PropFundamentalCloseDate";
        public static string PropCompany = "PropCompany";
        public static string PropPrincipalPartCloseDate = "PropPrincipalPartCloseDate";
        public static string PropFinishDate = "PropFinishDate";
        public static string PropRectificationConclusion = "PropRectificationConclusion";
        public static string PropProjNum = "PropProjNum";
        public static string PropSupervisorUnit = "PropSupervisorUnit";
        public static string PropDesignUnit = "PropDesignUnit";
        public static string PropStartDate = "PropStartDate";
        public static string PropContactValue = "PropContactValue";
        public static string PropDescription = "PropDescription";
        public static string PropProjectArea = "PropProjectArea";
        public static string PropProjName = "PropProjName";
        public static string PropProprietorUnit = "PropProprietorUnit";
    
        public static string PropConstructionScale = "PropConstructionScale";
        public static string PropProjClass = "PropProjClass";
        public static string PropProjClassDetail = "PropProjClassDetail";
        public static string PropProjectLevel = "PropProjectLevel";
        public static string PropIfcId = "PropIfcId";
        
        public static string ClassSecureNoticeSpecialCheck = "ClassSecureNoticeSpecialCheck";
        public static string ClassSecureNoticeWeeklyCheck = "ClassSecureNoticeWeeklyCheck";
          public static string ClassSecureNoticeDailyCheck = "ClassSecureNoticeDailyCheck";
          public static string ClassSecureIssue = "ClassSecureIssue";
        public static string ClassMonthReport = "ClassMonthReport";
        public static string ClassTaskApprove = "ClassTaskApprove";
        public static string ClassNotification = "ClassNotification";
        public static string ClassThreeControls = "ClassThreeControls";
        public static string ClassProjectHandOverList = "ClassProjectHandOverList";
        public static string ClassSecureNotice = "ClassSecureNotice";
        public static string ClassSecureReport = "ClassSecureReport";
        public static string ClassMonthlyEvaluationSecondLevelImportant = "ClassMonthlyEvaluationSecondLevelImportant";
        public static string ClassMonthlyEvaluationDirectlyControlImportant = "ClassMonthlyEvaluationDirectlyControlImportant";
        public static string ClassProject = "ClassProject";
        
        public static string OtContractor = "OtContractor";
        public static string ObjProject = "ObjProject";
        public static string OtWorkflow = "OtWorkflow";
        public static string OtSecureAdjustNotice = "OtSecureAdjustNotice";
        public static string OtSecureIssue = "OtSecureIssue";
        public static string ObjPart = "ObjPart";
        
        
        public static string WfsSecureAdjust = "WfsSecureAdjust";
        
    }
}